services:

  # Main Application
  mongo-api:
    build:
      context: business-domain/mongo-api/.
      dockerfile: Dockerfile
    image: mongo-api:v1.0
    container_name: mongo-api
    ports:
      - "8010:8010"
    environment:
      - MNG_DB_URL=mongodb
      - MNG_DB_PORT=27017
      - MNG_DB_COLLECTION=test
      - MNG_DB_USER=admin
      - MNG_DB_PASSWORD=admin
      - MNG_DB_AUTH_DB=admin
    depends_on:
      - mongodb
    networks:
      - mongo-api

  # Database for mongo-api
  mongodb:
    image: mongodb/mongodb-community-server:6.0.10-ubi9
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - /Users/pabloramosizquierdo/Desktop/Pablo/Tecnologias/Dockers/MongoDB/data:/data/db
    networks:
      - mongo-api

  # Jenkins Server for CI/CD
  # DOCKER -> socat TCP-LISTEN:2375,reuseaddr,fork UNIX-CONNECT:/var/run/docker.sock
  jenkins:
    build:
      context: infrastructure/jenkins/.
      dockerfile: Dockerfile
    image: jenkins-pablo:v1.0
    container_name: jenkins
    ports:
      - "8090:8090"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--httpPort=8090
    volumes:
      - /Users/pabloramosizquierdo/Desktop/Pablo/Tecnologias/Dockers/Jenkins/jenkins_home:/var/jenkins_home
    depends_on:
      - sonarqube
    networks:
      - mongo-api

  # PostgreSQL for SonarQube
  postgres:
    image: postgres:14.13 
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - /Users/pabloramosizquierdo/Desktop/Pablo/Tecnologias/Dockers/PostgreSQL/data_sonarqube:/var/lib/postgresql/data
    networks:
      - mongo-api

  # SonarQube for code quality analysis
  # admin/SonarQube1pab?
  # Token squ_f6707dc9c8ca74a578c0b72b29803fa777c54792
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - /Users/pabloramosizquierdo/Desktop/Pablo/Tecnologias/Dockers/Sonarqube/sonarqube_data:/opt/sonarqube/data
      - /Users/pabloramosizquierdo/Desktop/Pablo/Tecnologias/Dockers/Sonarqube/sonarqube_logs:/opt/sonarqube/logs
      - /Users/pabloramosizquierdo/Desktop/Pablo/Tecnologias/Dockers/Sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
    depends_on:
      - postgres
    networks:
      - mongo-api

  # Nexus Repository Manager
  nexus:
    image: sonatype/nexus3:3.82.0-alpine
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - /Users/pabloramosizquierdo/Desktop/Pablo/Tecnologias/Dockers/Nexus/nexus_data:/nexus-data
    networks:
      - mongo-api

  # Prometheus
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    ports:
      - "9090:9090"
    # Must be yml extension and not yaml
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./infrastructure/prometheus/basic_rules.yml:/etc/prometheus/basic_rules.yml
      - /Users/pabloramosizquierdo/Desktop/Pablo/Tecnologias/Dockers/Prometheus/data:/prometheus
    networks:
      - mongo-api

  # Grafana
  # https://grafana.com/grafana/dashboards/ -> To import dashboards pre-configured
  grafana:
    image: grafana/grafana:12.2.0-16868078697
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - /Users/pabloramosizquierdo/Desktop/Pablo/Tecnologias/Dockers/Grafana/grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mongo-api

networks:
  mongo-api:
    driver: bridge