###################
# Spring General ##
###################
spring.profiles.active=dev
server.port = 8010
application.name=@project.name@
application.version=@project.version@
application.description=@project.description@
info.app.java.source=@java.version@
info.app.encoding=@project.build.sourceEncoding@
info.app.maven.source=@maven.version@
info.app.firstName=@project.name@

####################
# BBDD Connection ##
####################
spring.data.mongodb.host=${MNG_DB_URL:localhost}
spring.data.mongodb.port=${MNG_DB_PORT:27017}
spring.data.mongodb.database=${MNG_DB_COLLECTION:test}
spring.data.mongodb.username=${MNG_DB_USER:admin}
spring.data.mongodb.password=${MNG_DB_PASSWORD:admin}
spring.data.mongodb.authentication-database=${MNG_DB_AUTH_DB:admin}

###################
## Metrics       ##
###################
# Expose all actuator endpoints. Not recommended for production.
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
