status = error
name = ConsoleOnlyConfig

property.LOG_PATTERN = %d{yyyy-MM-dd HH:mm:ss.SSS} | [%p] | %-40.40c : %m%n%throwable

appender.console.type = Console
appender.console.name = CONSOLE
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = ${LOG_PATTERN}

rootLogger.level = info
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = CONSOLE