services:
  jenkins:
    build:
      context: jenkins/.
      dockerfile: Dockerfile
    image: jenkins-pablo:v1.0
    container_name: jenkins
    ports:
      - "8090:8090"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--httpPort=8090
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home

  nexus:
    image: sonatype/nexus:2.15.2-03
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - ./nexus/nexus_data:/nexus-data